### ISSUE TITLE
elapsedSeconds has unnecessary float math

### ISSUE THREAD

**Issue by EeroFluge** [pfeerick/elapsedMillis#12]
The elapsedSeconds class uses millis()*0.001 several times, which requires conversion to float and then back to unsigned long.   I changed the expression to millis()/1000, which preserves integer math, and the class works as intended.   

Also, elapsedSeconds needs to be added to the Keywords file.

**Comment by pfeerick** [comment]
That it does... thanks for the suggestion! :) I'll make that change and push a new release it in the next day or so. I'd already corrected the `keywords.txt`, but either haven't committed or pushed it. Thanks for catching that too! 🙂

**Comment by pfeerick** [comment]
Committed in https://github.com/pfeerick/elapsedMillis/commit/bab00ea6fd9202b8f3ef344ac7abdfd06c173b91
