### ISSUE TITLE
Add installation info and elapsedSeconds to doc

### ISSUE THREAD

**Issue by drf5n** [pfeerick/elapsedMillis#15]
The main link for documentation for elapsedMillis seems to be  https://github.com/pfeerick/elapsedMillis/wiki but it doesn't document the elapsedSeconds code available in the library.

There is advice for installation on https://www.arduino.cc/reference/en/libraries/elapsedmillis/ to:

    To use this library, open the Library Manager in the Arduino IDE and install it from there.

Please add that installation line to the wiki.

The elapsedSeconds class is documented in the example and code:   https://github.com/pfeerick/elapsedMillis/blob/master/examples/blinkingLeds/blinkingLeds.ino
https://github.com/pfeerick/elapsedMillis/blob/765785e47e2ca87c8d8649c554f015e956e66667/elapsedMillis.h#L80 

Please add "elapsedSeconds" to the first header in https://github.com/pfeerick/elapsedMillis/wiki

Edit README.md to show:

The elapsedMillis, elapsedMicros, and elapsedSeconds special variable types (objects) automatically increase as time elapses. This makes it easy to check if a certain time has elapsed, while allowing your program to perform other work or checks for user input. It is also very to handle multiple tasks requiring different delays.

**Comment by paynterf** [comment]
The elapsedMillis, elapsedMicros, and elapsedSeconds special variable types (objects) automatically increase as time elapses. This makes it easy to check if a certain time has elapsed, while allowing your program to perform other work or checks for user input. It is also very **_easy_** to handle multiple tasks requiring different delays.
