### ISSUE TITLE
Could you ask for inclusion of this library in Arduino's Board Manager?

### ISSUE THREAD

**Issue by q2dg** [pfeerick/elapsedMillis#6]
This would give more visibility to this library, I think.
Thanks

**Comment by pfeerick** [comment]
Just waiting on the Arduino team to respond... the request is in [here](https://github.com/arduino/Arduino/issues/3577). They're just a bit slow at the moment as they are on holiday (it appears to be that time of year in Itally) :)

**Comment by pfeerick** [comment]
It's up now!

**Comment by q2dg** [comment]
Yeah! :-)
