### ISSUE TITLE
Please update library.properties

### ISSUE THREAD

**Issue by PaulStoffregen** [pfeerick/elapsedMillis#7]
I'm actually the author of this code.  ;-)

**Comment by Testato** [comment]
yes :-)
this is only a repackaging of your code ?
your code can directly run on arduino board ?

**Comment by pfeerick** [comment]
No problem Paul... just didn't want to make the presumption you wanted people emailing you about derivative works! ;-) 

Yes, this is a repackaging of Paul's code into a ready to use library, and some more examples thrown in.

**Comment by pfeerick** [comment]
Hey @PaulStoffregen... what email do you want me to use? Is paul@pjrc.com fine, or do you have another preference?
