### ISSUE TITLE
Include this library in PlatformIO

### ISSUE THREAD

**Issue by claybar** [pfeerick/elapsedMillis#8]
It would be great if this library could be incorporated into PlatformIIO's library manager.  I think all that is needed is a [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html) file, then register it with PlatformIO.

**Comment by pfeerick** [comment]
Has just been pushed to PlatformIO, waiting for moderation response before closing.

**Comment by pfeerick** [comment]
It's up now. http://platformio.org/lib/show/864/elapsedMillis

**Comment by claybar** [comment]
Great, thanks a lot.  One less library to manually manage.
